import "server-only";

import { createAdminClient } from "@/lib/supabase/admin";
import { formatNaira } from "@/lib/money";
import type { AiInsightSeverity } from "@/modules/shared/types";

type Admin = ReturnType<typeof createAdminClient>;
type DraftInsight = {
  kind: string;
  severity: AiInsightSeverity;
  title: string;
  body: string;
};

function lagosToday(): string {
  return new Intl.DateTimeFormat("en-CA", { timeZone: "Africa/Lagos" }).format(new Date());
}
function addDays(date: string, days: number): string {
  const d = new Date(`${date}T00:00:00Z`);
  d.setUTCDate(d.getUTCDate() + days);
  return d.toISOString().slice(0, 10);
}

/**
 * Proactive insights are RULE-BASED and grounded in Phase 5 aggregates + source
 * tables — never freeform model output (master spec Phase 6: "generated by
 * scheduled analysis, not freeform generation"). Every figure traces to a query.
 */
async function generateForCompany(admin: Admin, companyId: string): Promise<DraftInsight[]> {
  const out: DraftInsight[] = [];
  const today = lagosToday();

  // 1. Revenue trend — last 7 days vs the 7 before (company-wide daily_metrics).
  const windowStart = addDays(today, -13);
  const { data: metrics } = await admin
    .from("daily_metrics")
    .select("date, revenue")
    .eq("company_id", companyId)
    .is("branch_id", null)
    .gte("date", windowStart)
    .lte("date", today);
  const rows = (metrics as { date: string; revenue: number }[] | null) ?? [];
  const mid = addDays(today, -6);
  let recent = 0;
  let prior = 0;
  for (const r of rows) {
    if (r.date >= mid) recent += r.revenue;
    else prior += r.revenue;
  }
  if (prior > 0) {
    const pct = Math.round(((recent - prior) / prior) * 100);
    if (pct <= -20) {
      out.push({
        kind: "revenue_drop",
        severity: "danger",
        title: `Revenue down ${Math.abs(pct)}% this week`,
        body: `The last 7 days brought in ${formatNaira(recent)} versus ${formatNaira(prior)} the week before. Worth a look at sales and follow-ups.`,
      });
    } else if (pct >= 25) {
      out.push({
        kind: "revenue_up",
        severity: "positive",
        title: `Revenue up ${pct}% this week`,
        body: `The last 7 days brought in ${formatNaira(recent)}, up from ${formatNaira(prior)} the week before. Keep it going.`,
      });
    }
  }

  // 2. Low stock — items at/below threshold (event source for restock nudges).
  const { data: inv } = await admin
    .from("inventory")
    .select("quantity, low_stock_threshold, product:products(name, deleted_at)")
    .eq("company_id", companyId)
    .gt("low_stock_threshold", 0);
  type InvRow = { quantity: number; low_stock_threshold: number; product: { name: string; deleted_at: string | null } | null };
  const low = ((inv as unknown as InvRow[] | null) ?? []).filter(
    (r) => r.product && !r.product.deleted_at && r.quantity <= r.low_stock_threshold,
  );
  if (low.length > 0) {
    const names = low.slice(0, 3).map((r) => r.product!.name).join(", ");
    out.push({
      kind: "low_stock",
      severity: "warning",
      title: `${low.length} item${low.length === 1 ? "" : "s"} low on stock`,
      body: `${names}${low.length > 3 ? ` and ${low.length - 3} more` : ""} ${low.length === 1 ? "is" : "are"} at or below the restock threshold.`,
    });
  }

  // 3. Overdue invoices — money past its due date.
  const { data: overdue } = await admin
    .from("invoices")
    .select("id, total")
    .eq("company_id", companyId)
    .is("deleted_at", null)
    .in("status", ["unpaid", "partial", "overdue"])
    .lt("due_at", `${today}T00:00:00+01:00`);
  const odRows = (overdue as { id: string; total: number }[] | null) ?? [];
  if (odRows.length > 0) {
    const ids = odRows.map((r) => r.id);
    const { data: pays } = await admin.from("payments").select("invoice_id, amount").in("invoice_id", ids);
    const paid = new Map<string, number>();
    for (const p of (pays as { invoice_id: string; amount: number }[] | null) ?? []) {
      paid.set(p.invoice_id, (paid.get(p.invoice_id) ?? 0) + p.amount);
    }
    let outstanding = 0;
    let count = 0;
    for (const r of odRows) {
      const bal = Math.max(0, r.total - (paid.get(r.id) ?? 0));
      if (bal > 0) {
        outstanding += bal;
        count += 1;
      }
    }
    if (count > 0) {
      out.push({
        kind: "overdue",
        severity: "danger",
        title: `${formatNaira(outstanding)} overdue`,
        body: `${count} invoice${count === 1 ? "" : "s"} ${count === 1 ? "is" : "are"} past due. Sending reminders could bring this in.`,
      });
    }
  }

  return out;
}

/** Regenerate insights for every company. Idempotent: clear then re-insert. */
export async function runInsightsJob(): Promise<void> {
  const admin = createAdminClient();
  const { data: companies } = await admin.from("companies").select("id");
  for (const company of (companies as { id: string }[] | null) ?? []) {
    const drafts = await generateForCompany(admin, company.id);
    await admin.from("ai_insights").delete().eq("company_id", company.id);
    if (drafts.length > 0) {
      await admin.from("ai_insights").insert(
        drafts.map((d) => ({ company_id: company.id, ...d })),
      );
    }
  }
}
